- name: Installer les dépendances de PHP
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - php
    - php-mysql
    - php-fpm
    - libapache2-mod-php
    - php-cli
    - php-cgi
    - php-gd
  state: present

- name: Télécharger WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    mode: '0644'

- name: Extraire WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    creates: /var/www/html/wordpress
    remote_src: yes

- name: Copier le fichier de configuration WordPress
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php

